/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.beholder.memelang.ui;

import br.beholder.memelang.control.MainWindowController;
import br.beholder.memelang.model.analisador.Identificador;
import br.beholder.memelang.ui.swing.webLaf.WeblafUtils;
import br.beholder.memelang.ui.utils.ColorController;
import java.util.List;
import javax.swing.JTextArea;

/**
 *
 * @author lite
 */
public class MainPanel extends javax.swing.JPanel {
    
    int pX, pY;
    
    private MainWindowController controller;
    
    
    public MainPanel() {
        controller= new MainWindowController(this);
        initComponents();
        configurarCores();
    }
    private void configurarCores(){
        jPanel1.setBackground(ColorController.COR_PRINCIPAL);
        jPanel2.setBackground(ColorController.COR_PRINCIPAL);
        textEdit.setBackground(ColorController.COR_DESTAQUE);
        textEdit.setForeground(ColorController.COR_LETRA);
        console.setBackground(ColorController.FUNDO_ESCURO);
        console.setForeground(ColorController.COR_LETRA);
        WeblafUtils.instalaWeblaf();
        WeblafUtils.configuraWebLaf(jScrollPane1);
        WeblafUtils.configuraWebLaf(jScrollPane2);
        WeblafUtils.configurarBotao(compileButton, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 5);
        WeblafUtils.configurarBotao(openfileButton, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 5);
        WeblafUtils.configurarBotao(savefileButton, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 5);
        WeblafUtils.configurarBotao(generatetreeButton, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 5);
    }
    
    public JTextArea getTextAreaCodigo() {
        return textEdit;
    }

    public JTextArea getTextAreaMensagens() {
        return console;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textEdit = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        openfileButton = new com.alee.laf.button.WebButton();
        savefileButton = new com.alee.laf.button.WebButton();
        compileButton = new com.alee.laf.button.WebButton();
        generatetreeButton = new com.alee.laf.button.WebButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createEmptyBorder());
        setPreferredSize(new java.awt.Dimension(1024, 600));
        setLayout(new java.awt.BorderLayout(5, 5));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setLayout(new java.awt.BorderLayout(5, 5));

        textEdit.setColumns(20);
        textEdit.setRows(5);
        jScrollPane2.setViewportView(textEdit);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        openfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/beholder/memelang/ui/resources/stop.png"))); // NOI18N
        openfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openfileButtonActionPerformed(evt);
            }
        });
        jPanel1.add(openfileButton);

        savefileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/beholder/memelang/ui/resources/save.png"))); // NOI18N
        savefileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savefileButtonActionPerformed(evt);
            }
        });
        jPanel1.add(savefileButton);

        compileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/beholder/memelang/ui/resources/play.png"))); // NOI18N
        compileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compileButtonActionPerformed(evt);
            }
        });
        jPanel1.add(compileButton);

        generatetreeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/beholder/memelang/ui/resources/stop.png"))); // NOI18N
        generatetreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatetreeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(generatetreeButton);

        jPanel2.add(jPanel1, java.awt.BorderLayout.WEST);

        console.setEditable(false);
        console.setColumns(20);
        console.setRows(5);
        jScrollPane1.setViewportView(console);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void openfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openfileButtonActionPerformed
        this.controller.prepararCarregamentoArquivo();
    }//GEN-LAST:event_openfileButtonActionPerformed

    private void savefileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savefileButtonActionPerformed
        this.controller.prepararSalvamentoArquivo();
    }//GEN-LAST:event_savefileButtonActionPerformed

    private void compileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compileButtonActionPerformed
        this.controller.prepararCompilacao();
    }//GEN-LAST:event_compileButtonActionPerformed

    private void generatetreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatetreeButtonActionPerformed
        this.controller.exibirArvoreSintatica();
    }//GEN-LAST:event_generatetreeButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton compileButton;
    private javax.swing.JTextArea console;
    private com.alee.laf.button.WebButton generatetreeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.alee.laf.button.WebButton openfileButton;
    private com.alee.laf.button.WebButton savefileButton;
    private javax.swing.JTextArea textEdit;
    // End of variables declaration//GEN-END:variables
}
