/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.beholder.memelang.view;

import br.beholder.memelang.control.MainWindowController;
import br.beholder.memelang.model.language.MemelangLexer;
import br.beholder.memelang.model.language.MemelangParser;
import br.beholder.memelang.model.analisador.ErroLexico;
import br.beholder.memelang.model.analisador.FuncoesPadroes;
import br.beholder.memelang.model.analisador.Identificador;
import br.beholder.memelang.model.visitor.SemanticVisitor;
import java.util.Arrays;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.antlr.v4.gui.TreeViewer;
import org.antlr.v4.runtime.ANTLRInputStream;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;

/**
 *
 * @author Alisson
 */
public class MainWindow extends javax.swing.JFrame {
    public static List<Identificador> ids = null;
    private MainWindowController controller;
    
    /**
     * Creates new form NewJFrame
     */
    public MainWindow(MainWindowController ctr) {
        this.controller = ctr;
        initComponents();
        this.textAreaCodigo.setTabSize(4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaCodigo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textAreaCodigo.setColumns(20);
        textAreaCodigo.setRows(5);
        textAreaCodigo.setText("checkEm divideByZero L( )L illuminati\n\tcheckEm g = 1 desu\n\tcheckEm b = 2 desu\n\tyesButNo xoxo = trap desu\n\tbinLaden halflife = hacker100110101001 desu\n\n\twaitForIt L( checkEm i=0 desu i<10 desu i++ )L illuminati\n\t\teverydayUntilYouLikeIt L( yeah )L illuminati\n\t\t\tkek L( i == 5)L illuminati\n\t\t\t\tbatata a = \"s\" desu\n\t\t\t\tlolicon b = \"tuts tuts\" desu\n\t\t\tconfirmed\n\t\t\tnotSureIf illuminati\n\t\t\t\tfirst lel desu\n\t\t\t\tb = \"Morre\" desu\n\t\t\tconfirmed\n\t\tconfirmed\n\tconfirmed\nconfirmed");
        jScrollPane1.setViewportView(textAreaCodigo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(690, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ANTLRInputStream ais = new ANTLRInputStream(textAreaCodigo.getText());//*
        MemelangLexer lexer = new MemelangLexer(ais);//*
        CommonTokenStream stream = new CommonTokenStream(lexer);//*
        MemelangParser parser = new MemelangParser(stream);//*
        lexer.removeErrorListeners();
        parser.removeErrorListeners();

        // Instala o tratador de erros personalizado que irá exibir as mensagens
        // em tela na JList
        ErroLexico erro = new ErroLexico();
        lexer.addErrorListener(erro);
        parser.addErrorListener(erro);
        
        if (erro.getErrors().isEmpty())
        {
            ParseTree tree = parser.prog(); //*
            JFrame frame = new JFrame("Antlr AST");
            JPanel panel = new JPanel();
            TreeViewer viewr = new TreeViewer(Arrays.asList(parser.getRuleNames()),tree);
            viewr.setScale(1);//scale a little
            panel.add(viewr);
            frame.add(panel);
            frame.setSize(200,200);
            frame.setVisible(true);
            System.out.println("oi");
            
        }
        for (String errin : erro.getErrors())
        {
            System.out.println(errin);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaCodigo;
    // End of variables declaration//GEN-END:variables
}
