/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.beholder.memelang.view;

import br.beholder.memelang.control.MainWindowController;
import br.beholder.memelang.model.analisador.Identificador;
import com.alee.laf.WebLookAndFeel;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Alisson
 */
public class MainWindow extends javax.swing.JFrame {
    public static List<Identificador> ids = null;
    private MainWindowController controller;
    
    /**
     * Creates new form NewJFrame
     */
    public MainWindow(MainWindowController ctr) {
        this.controller = ctr;
        try {
            javax.swing.UIManager.setLookAndFeel(new WebLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        this.setButtonColor(this.botaoCarregarArquivo, Color.WHITE, Color.WHITE, Color.BLACK, Color.RED, Color.DARK_GRAY, Color.RED);
        this.setButtonColor(this.botaoCompilar, Color.WHITE, Color.WHITE, Color.BLACK, Color.RED, Color.DARK_GRAY, Color.RED);
        this.setButtonColor(this.botaoGerarArvore, Color.WHITE, Color.WHITE, Color.BLACK, Color.RED, Color.DARK_GRAY, Color.RED);
        this.setButtonColor(this.botaoSalvar, Color.WHITE, Color.WHITE, Color.BLACK, Color.RED, Color.DARK_GRAY, Color.RED);
        this.getContentPane().setBackground(Color.WHITE);
        this.textAreaCodigo.setTabSize(4);
    }

    private void setButtonColor(com.alee.laf.button.WebButton b, Color fore, Color selFor, Color top, Color topSel, Color bot, Color botSel){
        b.setForeground (fore);
        b.setSelectedForeground (selFor);
        b.setTopBgColor (top);
        b.setTopSelectedBgColor (topSel);
        b.setBottomBgColor (bot);
        b.setBottomSelectedBgColor (botSel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneCodigo = new javax.swing.JScrollPane();
        textAreaCodigo = new javax.swing.JTextArea();
        scrollPanelMensagens = new javax.swing.JScrollPane();
        textAreaMensagens = new javax.swing.JTextArea();
        painelBotoesFooter = new javax.swing.JPanel();
        botaoCompilar = new com.alee.laf.button.WebButton();
        botaoCarregarArquivo = new com.alee.laf.button.WebButton();
        botaoSalvar = new com.alee.laf.button.WebButton();
        botaoGerarArvore = new com.alee.laf.button.WebButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meme Language IDE");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 600));

        scrollPaneCodigo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 51, 51), new java.awt.Color(255, 153, 153)));

        textAreaCodigo.setColumns(20);
        textAreaCodigo.setRows(5);
        textAreaCodigo.setText("checkEm divideByZero L( )L illuminati\n\tcheckEm g = 1 desu\n\tcheckEm b = 2 desu\n\tyesButNo xoxo = trap desu\n\tbinLaden halflife = hacker100110101001 desu\n\n\twaitForIt L( checkEm i=0 desu i<10 desu i++ )L illuminati\n\t\teverydayUntilYouLikeIt L( yeah )L illuminati\n\t\t\tkek L( i == 5)L illuminati\n\t\t\t\tbatata a = \"s\" desu\n\t\t\t\tlolicon b = \"tuts tuts\" desu\n\t\t\tconfirmed\n\t\t\tnotSureIf illuminati\n\t\t\t\tfirst lel desu\n\t\t\t\tb = \"Morre\" desu\n\t\t\tconfirmed\n\t\tconfirmed\n\tconfirmed\nconfirmed");
        scrollPaneCodigo.setViewportView(textAreaCodigo);

        scrollPanelMensagens.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 2, true));

        textAreaMensagens.setEditable(false);
        textAreaMensagens.setColumns(20);
        textAreaMensagens.setRows(5);
        scrollPanelMensagens.setViewportView(textAreaMensagens);

        painelBotoesFooter.setBackground(new java.awt.Color(255, 255, 255));

        botaoCompilar.setText("Compilar");
        botaoCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCompilarActionPerformed(evt);
            }
        });

        botaoCarregarArquivo.setText("Carregar Arquivo");
        botaoCarregarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCarregarArquivoActionPerformed(evt);
            }
        });

        botaoSalvar.setText("Salvar Arquivo");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoGerarArvore.setText("Gerar Árvore");
        botaoGerarArvore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarArvoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesFooterLayout = new javax.swing.GroupLayout(painelBotoesFooter);
        painelBotoesFooter.setLayout(painelBotoesFooterLayout);
        painelBotoesFooterLayout.setHorizontalGroup(
            painelBotoesFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesFooterLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(botaoCarregarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(botaoCompilar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoGerarArvore, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        painelBotoesFooterLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoCarregarArquivo, botaoCompilar, botaoGerarArvore, botaoSalvar});

        painelBotoesFooterLayout.setVerticalGroup(
            painelBotoesFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelBotoesFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(botaoCarregarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCompilar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoGerarArvore, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneCodigo)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(scrollPanelMensagens)
                .addGap(223, 223, 223))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(painelBotoesFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(311, 311, 311))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(scrollPanelMensagens, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(painelBotoesFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCompilarActionPerformed
        this.controller.prepararCompilacao();
    }//GEN-LAST:event_botaoCompilarActionPerformed

    private void botaoCarregarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCarregarArquivoActionPerformed
        this.controller.prepararCarregamentoArquivo();
    }//GEN-LAST:event_botaoCarregarArquivoActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        this.controller.prepararSalvamentoArquivo();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoGerarArvoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarArvoreActionPerformed
        this.controller.exibirArvoreSintatica();
    }//GEN-LAST:event_botaoGerarArvoreActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow(null).setVisible(true);
            }
        });
    }

    
    public JTextArea getTextAreaCodigo() {
        return textAreaCodigo;
    }

    public JTextArea getTextAreaMensagens() {
        return textAreaMensagens;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton botaoCarregarArquivo;
    private com.alee.laf.button.WebButton botaoCompilar;
    private com.alee.laf.button.WebButton botaoGerarArvore;
    private com.alee.laf.button.WebButton botaoSalvar;
    private javax.swing.JPanel painelBotoesFooter;
    private javax.swing.JScrollPane scrollPaneCodigo;
    private javax.swing.JScrollPane scrollPanelMensagens;
    private javax.swing.JTextArea textAreaCodigo;
    private javax.swing.JTextArea textAreaMensagens;
    // End of variables declaration//GEN-END:variables
}
